--------------------------------------------------------
--  파일이 생성됨 - 목요일-4월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SAWON
--------------------------------------------------------

  CREATE TABLE "BIT901"."SAWON" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"BUSEO" VARCHAR2(20 BYTE), 
	"GIBON" NUMBER(10,0), 
	"SUDANG" NUMBER(10,0), 
	"WRITEDAY" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into BIT901.SAWON
SET DEFINE OFF;
Insert into BIT901.SAWON (NUM,NAME,BUSEO,GIBON,SUDANG,WRITEDAY) values (1,'김단비','인사부',450,90,to_date('22/04/13','RR/MM/DD'));
Insert into BIT901.SAWON (NUM,NAME,BUSEO,GIBON,SUDANG,WRITEDAY) values (2,'이효리','교육부',560,15,to_date('22/04/13','RR/MM/DD'));
Insert into BIT901.SAWON (NUM,NAME,BUSEO,GIBON,SUDANG,WRITEDAY) values (3,'유재석','홍보부',589,11,to_date('22/04/13','RR/MM/DD'));
Insert into BIT901.SAWON (NUM,NAME,BUSEO,GIBON,SUDANG,WRITEDAY) values (4,'강호동','인사부',780,45,to_date('22/04/13','RR/MM/DD'));
Insert into BIT901.SAWON (NUM,NAME,BUSEO,GIBON,SUDANG,WRITEDAY) values (5,'남주혁','인사부',600,80,to_date('22/04/13','RR/MM/DD'));
Insert into BIT901.SAWON (NUM,NAME,BUSEO,GIBON,SUDANG,WRITEDAY) values (6,'남주혁','교육부',560,40,to_date('22/04/14','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SAWON_PK_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "BIT901"."SAWON_PK_NUM" ON "BIT901"."SAWON" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SAWON
--------------------------------------------------------

  ALTER TABLE "BIT901"."SAWON" ADD CONSTRAINT "SAWON_PK_NUM" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;